sudo: required
services:
  - docker
language: generic

before_install:
  - docker build -t jgddocker/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true jgddocker/docker-react npm run test
  #  - docker run USERNAME/docker-react npm run test -- --coverage
