sudo: required
services:
  - docker
language: generic

before_install:
  - docker build -t jgddocker/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true jgddocker/docker-react npm run test 
deploy:
  edge: true
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "docker-env-react"
  env: "DockerEnvReact-env"
  bucket_name: "elasticbeanstalk-eu-west-3-976616965054"
  bucket_path: "docker-env-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"